SRCS=informe4

all:
	pdflatex $(SRCS).tex
clean:
	rm -rf $(SRCS).aux
	rm -rf $(SRCS).log
	rm -rf $(SRCS).dvi
	rm -rf $(SRCS).ps
	rm -rf $(SRCS).out
	rm -rf $(SRCS).snm
	rm -rf $(SRCS).toc
	rm -rf $(SRCS).nav
	rm -rf $(SRCS).pdf
	rm -rf *~
